/* GENERATED by build-tokens.mjs — do not edit by hand. Re-run after /fig-sync. */
export const tokens = {
  "colors": {
    "core": {
      "white": "var(--core-white)",
      "black": "var(--core-black)"
    },
    "content": {
      "primary": "var(--content-primary)",
      "secondary": "var(--content-secondary)",
      "tertiary": "var(--content-tertiary)",
      "inverseprimary": "var(--content-inverseprimary)",
      "inversesecondary": "var(--content-inversesecondary)",
      "inversetertiary": "var(--content-inversetertiary)",
      "extensions": {
        "error": "var(--content-extensions-error)",
        "warning": "var(--content-extensions-warning)",
        "success": "var(--content-extensions-success)",
        "info": "var(--content-extensions-info)"
      },
      "brand": {
        "brand": "var(--content-brand-brand)",
        "accent": "var(--content-brand-accent)"
      }
    },
    "border": {
      "primary": "var(--border-primary)",
      "secondary": "var(--border-secondary)",
      "tertiary": "var(--border-tertiary)",
      "inverseprimary": "var(--border-inverseprimary)",
      "inversesecondary": "var(--border-inversesecondary)",
      "inversetertiary": "var(--border-inversetertiary)",
      "hoveroverlay": "var(--border-hoveroverlay)",
      "inversehoveroverlay": "var(--border-inversehoveroverlay)",
      "extensions": {
        "success": "var(--border-extensions-success)",
        "warning": "var(--border-extensions-warning)",
        "info": "var(--border-extensions-info)",
        "error": "var(--border-extensions-error)"
      },
      "brand": {
        "brand": "var(--border-brand-brand)",
        "accent": "var(--border-brand-accent)"
      }
    },
    "background": {
      "primary": "var(--background-primary)",
      "secondary": "var(--background-secondary)",
      "tertiary": "var(--background-tertiary)",
      "inverseprimary": "var(--background-inverseprimary)",
      "inversesecondary": "var(--background-inversesecondary)",
      "inversetertiary": "var(--background-inversetertiary)",
      "hoveroverlay": "var(--background-hoveroverlay)",
      "inversehoveroverlay": "var(--background-inversehoveroverlay)",
      "extensions": {
        "error": "var(--background-extensions-error)",
        "warning": "var(--background-extensions-warning)",
        "info": "var(--background-extensions-info)",
        "success": "var(--background-extensions-success)"
      },
      "hover": "var(--background-hover)",
      "brand": {
        "brand": "var(--background-brand-brand)",
        "accent": "var(--background-brand-accent)"
      }
    },
    "shadow": {
      "2xl": "var(--shadow-2xl)",
      "lg": "var(--shadow-lg)",
      "md": "var(--shadow-md)",
      "xs": "var(--shadow-xs)",
      "sm": "var(--shadow-sm)",
      "xl": "var(--shadow-xl)"
    },
    "components": {
      "tags": {
        "background": {
          "teal": "var(--components-tags-background-teal)",
          "green": "var(--components-tags-background-green)",
          "emerald": "var(--components-tags-background-emerald)",
          "sky": "var(--components-tags-background-sky)",
          "yellow": "var(--components-tags-background-yellow)",
          "pink": "var(--components-tags-background-pink)",
          "violet": "var(--components-tags-background-violet)",
          "fuchsia": "var(--components-tags-background-fuchsia)",
          "red": "var(--components-tags-background-red)",
          "purple": "var(--components-tags-background-purple)",
          "cyan": "var(--components-tags-background-cyan)",
          "lime": "var(--components-tags-background-lime)",
          "indigo": "var(--components-tags-background-indigo)",
          "amber": "var(--components-tags-background-amber)",
          "orange": "var(--components-tags-background-orange)",
          "zinc": "var(--components-tags-background-zinc)",
          "blue": "var(--components-tags-background-blue)",
          "rose": "var(--components-tags-background-rose)"
        },
        "content": {
          "sky": "var(--components-tags-content-sky)",
          "teal": "var(--components-tags-content-teal)",
          "emerald": "var(--components-tags-content-emerald)",
          "green": "var(--components-tags-content-green)",
          "amber": "var(--components-tags-content-amber)",
          "yellow": "var(--components-tags-content-yellow)",
          "rose": "var(--components-tags-content-rose)",
          "pink": "var(--components-tags-content-pink)",
          "violet": "var(--components-tags-content-violet)",
          "zinc": "var(--components-tags-content-zinc)",
          "cyan": "var(--components-tags-content-cyan)",
          "fuchsia": "var(--components-tags-content-fuchsia)",
          "indigo": "var(--components-tags-content-indigo)",
          "blue": "var(--components-tags-content-blue)",
          "purple": "var(--components-tags-content-purple)",
          "orange": "var(--components-tags-content-orange)",
          "lime": "var(--components-tags-content-lime)",
          "red": "var(--components-tags-content-red)"
        },
        "border": {
          "sky": "var(--components-tags-border-sky)",
          "cyan": "var(--components-tags-border-cyan)",
          "green": "var(--components-tags-border-green)",
          "lime": "var(--components-tags-border-lime)",
          "amber": "var(--components-tags-border-amber)",
          "pink": "var(--components-tags-border-pink)",
          "zinc": "var(--components-tags-border-zinc)",
          "rose": "var(--components-tags-border-rose)",
          "indigo": "var(--components-tags-border-indigo)",
          "purple": "var(--components-tags-border-purple)",
          "violet": "var(--components-tags-border-violet)",
          "emerald": "var(--components-tags-border-emerald)",
          "fuchsia": "var(--components-tags-border-fuchsia)",
          "yellow": "var(--components-tags-border-yellow)",
          "teal": "var(--components-tags-border-teal)",
          "orange": "var(--components-tags-border-orange)",
          "blue": "var(--components-tags-border-blue)",
          "red": "var(--components-tags-border-red)"
        }
      },
      "buttons": {
        "primary": {
          "background": {
            "disabled": "var(--components-buttons-primary-background-disabled)",
            "focus": "var(--components-buttons-primary-background-focus)",
            "pressed": "var(--components-buttons-primary-background-pressed)",
            "hover": "var(--components-buttons-primary-background-hover)",
            "default": "var(--components-buttons-primary-background-default)"
          },
          "border": {
            "focus": "var(--components-buttons-primary-border-focus)",
            "disabled": "var(--components-buttons-primary-border-disabled)",
            "pressed": "var(--components-buttons-primary-border-pressed)",
            "hover": "var(--components-buttons-primary-border-hover)",
            "default": "var(--components-buttons-primary-border-default)"
          }
        },
        "secondary": {
          "background": {
            "default": "var(--components-buttons-secondary-background-default)",
            "hover": "var(--components-buttons-secondary-background-hover)",
            "pressed": "var(--components-buttons-secondary-background-pressed)",
            "focus": "var(--components-buttons-secondary-background-focus)",
            "disabled": "var(--components-buttons-secondary-background-disabled)"
          },
          "border": {
            "disabled": "var(--components-buttons-secondary-border-disabled)",
            "focus": "var(--components-buttons-secondary-border-focus)",
            "pressed": "var(--components-buttons-secondary-border-pressed)",
            "hover": "var(--components-buttons-secondary-border-hover)",
            "default": "var(--components-buttons-secondary-border-default)"
          }
        },
        "outline": {
          "background": {
            "default": "var(--components-buttons-outline-background-default)",
            "hover": "var(--components-buttons-outline-background-hover)",
            "pressed": "var(--components-buttons-outline-background-pressed)",
            "focus": "var(--components-buttons-outline-background-focus)",
            "disabled": "var(--components-buttons-outline-background-disabled)"
          },
          "border": {
            "disabled": "var(--components-buttons-outline-border-disabled)",
            "focus": "var(--components-buttons-outline-border-focus)",
            "pressed": "var(--components-buttons-outline-border-pressed)",
            "hover": "var(--components-buttons-outline-border-hover)",
            "default": "var(--components-buttons-outline-border-default)"
          }
        }
      }
    }
  },
  "spacing": {
    "0": "0px",
    "1": "4px",
    "2": "8px",
    "3": "12px",
    "4": "16px",
    "5": "20px",
    "6": "24px",
    "7": "28px",
    "8": "32px",
    "9": "36px",
    "10": "40px",
    "11": "44px",
    "12": "48px",
    "14": "56px",
    "16": "64px",
    "20": "80px",
    "24": "96px",
    "28": "112px",
    "32": "128px",
    "36": "144px",
    "40": "160px",
    "44": "176px",
    "48": "192px",
    "52": "208px",
    "56": "224px",
    "60": "240px",
    "64": "256px",
    "72": "288px",
    "80": "320px",
    "96": "384px",
    "px": "1px",
    "0.5": "2px",
    "1.5": "6px",
    "2.5": "10px",
    "3.5": "14px"
  },
  "borderRadius": {
    "sm": "2px",
    "none": "0px",
    "DEFAULT": "4px",
    "md": "6px",
    "lg": "8px",
    "xl": "12px",
    "2xl": "16px",
    "3xl": "24px",
    "full": "9999px"
  },
  "fontSize": {
    "display-extra-large": [
      "128px",
      {
        "lineHeight": "141px"
      }
    ],
    "display-large": [
      "96px",
      {
        "lineHeight": "106px"
      }
    ],
    "display-medium": [
      "72px",
      {
        "lineHeight": "79px"
      }
    ],
    "display-small": [
      "64px",
      {
        "lineHeight": "70px"
      }
    ],
    "display-tiny": [
      "48px",
      {
        "lineHeight": "53px"
      }
    ],
    "heading-extra-large": [
      "36px",
      {
        "lineHeight": "40px"
      }
    ],
    "heading-large": [
      "30px",
      {
        "lineHeight": "33px"
      }
    ],
    "heading-medium": [
      "24px",
      {
        "lineHeight": "26px"
      }
    ],
    "heading-small": [
      "20px",
      {
        "lineHeight": "22px"
      }
    ],
    "heading-tiny": [
      "16px",
      {
        "lineHeight": "18px"
      }
    ],
    "label-large": [
      "20px",
      {
        "lineHeight": "20px"
      }
    ],
    "label-base": [
      "16px",
      {
        "lineHeight": "16px"
      }
    ],
    "label-small": [
      "14px",
      {
        "lineHeight": "14px"
      }
    ],
    "label-tiny": [
      "12px",
      {
        "lineHeight": "12px"
      }
    ],
    "paragraph-large": [
      "20px",
      {
        "lineHeight": "28px"
      }
    ],
    "paragraph-base": [
      "16px",
      {
        "lineHeight": "22px"
      }
    ],
    "paragraph-small": [
      "14px",
      {
        "lineHeight": "20px"
      }
    ],
    "paragraph-tiny": [
      "12px",
      {
        "lineHeight": "17px"
      }
    ],
    "subtitle-large": [
      "24px",
      {
        "lineHeight": "29px"
      }
    ],
    "subtitle-base": [
      "20px",
      {
        "lineHeight": "24px"
      }
    ],
    "subtitle-small": [
      "16px",
      {
        "lineHeight": "19px"
      }
    ]
  }
} as const;
